"""
data_pipeline.py
----------------
Discovers, validates, and merges all compatible symptom-disease CSV datasets
from data/raw/ into a single deduplicated file at data/merged/combined.csv.

Compatible schema: 132 binary symptom columns + 'prognosis' (41 disease labels).
Any CSV in data/raw/ that has this schema is automatically merged.

══════════════════════════════════════════════════════════════════════════════
DATASETS WITH THIS EXACT SCHEMA
══════════════════════════════════════════════════════════════════════════════

1. Symbipredict 2022  [already present — 304 rows]
   Source: data/raw/symbipredict_2022.csv

2. Disease Prediction Dataset — Kaushil Bhavsar  [Kaggle, free, ~4920 rows]
   Same 132 symptoms, same 41 diseases, same binary encoding.
   Download:
     pip install kaggle
     # Place kaggle.json in ~/.kaggle/ (from kaggle.com -> Settings -> API)
     kaggle datasets download -d kaushil268/disease-prediction-using-machine-learning --unzip -p data/raw/

3. Disease Symptom Dataset — itachi9604  [Kaggle, free, ~5000 rows]
   Download:
     kaggle datasets download -d itachi9604/disease-symptom-description-dataset --unzip -p data/raw/
     # Only Training.csv is compatible — Testing.csv lacks the prognosis column

══════════════════════════════════════════════════════════════════════════════
DATASETS WITH DIFFERENT SCHEMAS (converted by ddxplus_adapter.py)
══════════════════════════════════════════════════════════════════════════════

• DDXPlus (Intelia, 2022) — 1.6 M synthetic patient cases, 49 diseases, 1 230 features
  Validated by family medicine physicians.  Run the adapter first, then this pipeline
  auto-discovers the output CSV:
    python training/ddxplus_adapter.py --source ddxplus
  https://huggingface.co/datasets/Neko-Nik/DDXPlus

• Columbia EHR Dataset (Rotmensch et al., 2017)
  Disease–symptom probability table derived from 270 k de-identified EHR records.
  The adapter converts the matrix to binary patient rows:
    python training/ddxplus_adapter.py --source columbia
  https://figshare.com/articles/dataset/Disease_Symptom_and_Patient_Profile_Dataset/

══════════════════════════════════════════════════════════════════════════════
FEEDBACK DATA (generated by the platform)
══════════════════════════════════════════════════════════════════════════════

The Spring Boot backend stores patient feedback (was_correct + doctor_diagnosis)
in the symptom_feedback table. A future export step can turn confirmed rows into
additional training data by matching report symptom_text -> symptom vector.

══════════════════════════════════════════════════════════════════════════════
USAGE
══════════════════════════════════════════════════════════════════════════════

  # Step 1 — add datasets to data/raw/ (see download instructions above)
  # Step 2 — run this pipeline
  python training/data_pipeline.py

  # Step 3 — retrain with the merged dataset
  python training/train_model.py
"""
from __future__ import annotations

import os
import shutil
import subprocess

import pandas as pd


def _kaggle_api():
    """Return an authenticated KaggleApi instance, or None if kaggle is not installed."""
    try:
        from kaggle import KaggleApi          # new-style (v1.7+)
        api = KaggleApi()
        api.authenticate()
        return api
    except ImportError:
        return None
    except Exception as exc:
        print(f"    Kaggle auth failed: {exc}")
        return None

BASE_DIR   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW_DIR    = os.path.join(BASE_DIR, "data", "raw")
MERGED_DIR = os.path.join(BASE_DIR, "data", "merged")
OUT_PATH   = os.path.join(MERGED_DIR, "combined.csv")

_ANCHOR    = os.path.join(RAW_DIR, "symbipredict_2022.csv")

# Kaggle datasets to auto-download if the CLI is available
_KAGGLE_DATASETS = [
    {
        "id":       "kaushil268/disease-prediction-using-machine-learning",
        "files":    ["Training.csv", "training.csv"],
        "save_as":  "kaushil_training.csv",
        "desc":     "Disease Prediction (Kaushil Bhavsar) — same 132-symptom schema",
        "note":     "Derived from the same synthetic source as Symbipredict — adds few new unique rows after dedup.",
    },
]


def _try_kaggle_download(dataset_id: str, target_dir: str) -> bool:
    """Attempt a Kaggle dataset download via Python API. Returns True on success."""
    api = _kaggle_api()
    if api is None:
        return False
    try:
        os.makedirs(target_dir, exist_ok=True)
        api.dataset_download_files(dataset_id, path=target_dir, unzip=True, quiet=False)
        return True
    except Exception as exc:
        print(f"    Download error: {exc}")
        return False


# Known spelling/casing differences across datasets — maps lowercased variant → canonical
_LABEL_CORRECTIONS = {
    "osteoarthristis":                          "osteoarthritis",
    "dimorphic hemmorhoids(piles)":             "dimorphic hemmorhoids (piles)",
    "chicken pox":                              "chickenpox",
    "peptic ulcer diseae":                      "peptic ulcer disease",
    "(vertigo) paroymsal  positional vertigo":  "vertigo",
    "alcoholic hepatitis":                      "alcoholic hepatitis",  # keep; handled by title-case
}


def _normalise_labels(series: pd.Series, canonical: set[str]) -> pd.Series:
    """
    Normalise a prognosis column so all labels match the anchor canonical names.
    Steps: strip whitespace → lowercase → apply typo corrections → re-apply canonical casing.
    Rows whose label cannot be resolved are left as-is (they will be filtered later).
    """
    # Build a lookup: lowercase canonical → canonical (so we can restore casing)
    lower_to_canon = {c.lower(): c for c in canonical}

    def fix(raw: str) -> str:
        cleaned = raw.strip().lower()
        corrected = _LABEL_CORRECTIONS.get(cleaned, cleaned)
        return lower_to_canon.get(corrected, raw)   # unknown labels pass through unchanged

    return series.map(fix)


def _load_if_compatible(
    path: str, symptom_cols: list[str], canonical_diseases: set[str]
) -> pd.DataFrame | None:
    """
    Return a filtered DataFrame if the CSV has the required symptom schema.
    Normalises disease labels and drops rows for unknown diseases.
    """
    try:
        df = pd.read_csv(path)
        if "prognosis" not in df.columns:
            return None
        missing = set(symptom_cols) - set(df.columns)
        if missing:
            return None
        df = df[symptom_cols + ["prognosis"]].copy()
        df["prognosis"] = _normalise_labels(df["prognosis"], canonical_diseases)
        df = df[df["prognosis"].isin(canonical_diseases)]
        return df if len(df) > 0 else None
    except Exception:
        return None


def build() -> str:
    """
    Merge all compatible datasets found in data/raw/ into data/merged/combined.csv.
    Returns the path to the combined file.
    """
    os.makedirs(MERGED_DIR, exist_ok=True)

    # ── anchor: derive canonical column list + known disease set ──────────────
    anchor           = pd.read_csv(_ANCHOR).drop_duplicates()
    sym_cols         = [c for c in anchor.columns if c != "prognosis"]
    canonical_diseases = set(anchor.prognosis.unique())
    frames    = [anchor]
    print(f"\nAnchor : {_ANCHOR}")
    print(f"         {len(anchor)} rows | {len(sym_cols)} symptom columns | "
          f"{anchor.prognosis.nunique()} diseases")

    # ── try Kaggle auto-downloads ──────────────────────────────────────────────
    has_kaggle = _kaggle_api() is not None
    for ds in _KAGGLE_DATASETS:
        print(f"\nDataset: {ds['desc']}")
        already_present = False
        check_names = ds["files"] + ([ds["save_as"]] if "save_as" in ds else [])
        for fname in check_names:
            candidate = os.path.join(RAW_DIR, fname)
            if os.path.exists(candidate):
                df = _load_if_compatible(candidate, sym_cols, canonical_diseases)
                if df is not None:
                    print(f"  Found existing {fname}: {len(df)} rows — added")
                    if ds.get("note"):
                        print(f"  Note: {ds['note']}")
                    frames.append(df)
                    already_present = True
                    break

        if already_present:
            continue

        if has_kaggle:
            tmp = os.path.join(RAW_DIR, "_kaggle_tmp")
            print(f"  Downloading via Kaggle API...")
            if _try_kaggle_download(ds["id"], tmp):
                for fname in ds["files"]:
                    src = os.path.join(tmp, fname)
                    if os.path.exists(src):
                        df = _load_if_compatible(src, sym_cols, canonical_diseases)
                        if df is not None:
                            save_name = ds.get("save_as", fname)
                            dst = os.path.join(RAW_DIR, save_name)
                            shutil.move(src, dst)
                            print(f"  Saved as {save_name}: {len(df)} rows — added")
                            if ds.get("note"):
                                print(f"  Note: {ds['note']}")
                            frames.append(df)
                            break
                shutil.rmtree(tmp, ignore_errors=True)
            else:
                print(f"  Download failed. Add manually:")
                print(f"    kaggle datasets download -d {ds['id']} --unzip -p data/raw/")
        else:
            print(f"  Kaggle not available. To add this dataset:")
            print(f"    pip install kaggle")
            print(f"    # Place kaggle.json in C:\\Users\\<you>\\.kaggle\\  (from kaggle.com -> Settings -> API)")
            print(f"    Then re-run: python training/data_pipeline.py")

    # ── scan raw/ for any other compatible CSVs ────────────────────────────────
    for fname in sorted(os.listdir(RAW_DIR)):
        if not fname.endswith(".csv"):
            continue
        path = os.path.join(RAW_DIR, fname)
        if path == _ANCHOR:
            continue
        # Skip files already loaded from Kaggle
        if any(path == os.path.join(RAW_DIR, f) for ds in _KAGGLE_DATASETS for f in ds["files"]):
            continue
        df = _load_if_compatible(path, sym_cols, canonical_diseases)
        if df is not None:
            print(f"\nExtra  : {fname}: {len(df)} rows — added")
            frames.append(df)

    # ── merge and save ─────────────────────────────────────────────────────────
    combined = pd.concat(frames, ignore_index=True).drop_duplicates()
    combined.to_csv(OUT_PATH, index=False)

    per_disease = combined.groupby("prognosis").size()
    print(f"\n{'='*60}")
    print(f"  Combined dataset : {len(combined)} rows  ({OUT_PATH})")
    print(f"  Diseases         : {combined.prognosis.nunique()}")
    print(f"  Rows/disease     : avg {per_disease.mean():.1f}  "
          f"min {per_disease.min()}  max {per_disease.max()}")
    print(f"{'='*60}")
    print(f"\nNext step: python training/train_model.py")
    return OUT_PATH


if __name__ == "__main__":
    build()
